# Generated by Django 4.2.6 on 2023-10-27 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(code='invalid_isbn', message='Invalid ISBN format. Please use XXX-XX-XXXXX-X format.', regex='^\\d{3}-\\d{2}-\\d{5}-\\d{1}$')]),
        ),
    ]
